site_name: Linolium
site_description: Automated phylogenetic lineage proposal and interactive curation

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Usage Guide: usage.md
